server:
  port: ${SERVER_PORT}

grpc:
  server:
    port: ${GRPC_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  # なんかSpring起動するたびに謎の警告が出るので抑制falseに。　falseが推奨らしい。
  # https://tosi-tech.net/2018/08/open-session-in-view-pattern/
  jpa.open-in-view: false

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

aws:
  cognito:
    user-pool-id: ${AWS_COGNITO_USER-POOL-ID}
    client-id: ${AWS_COGNITO_CLIENT-ID}