spring:
  profiles:
    active: local
    group:
      local:
        - app-common
        - app-local
        - axon-server
        - datastore-mysql
      local-with-axoniq:
        - app-common
        - app-local
        - axon-server
        - axoniq-console
        - datastore-mysql
      integration-test:
        - app-integration-test
      test:
        - app-common
        - app-test
        - axon-server
        - axoniq-console
        - datastore-mysql
      prod:
        - app-common
        - app-prod
        - axon-server
        - axoniq-console
        - datastore-mysql